# Generated by Django 4.2.4 on 2023-09-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_file',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
