# Generated by Django 4.2.4 on 2023-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_model', '0003_camera_alter_imagemodel_image_file_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='cameras',
            new_name='selected_cameras',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='access_all_cameras',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_type',
            field=models.CharField(choices=[('allCameras', 'Access all cameras'), ('chooseCamera', 'Choose cameras access')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
