# Generated by Django 4.2.4 on 2023-09-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cctv_model', '0004_delete_imagemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCameraAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv_model.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'camera')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
