# Generated by Django 4.2.4 on 2023-09-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cctv_model', '0005_usercameraaccess_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('allCameras', 'All cameras'), ('chooseCamera', 'Choose cameras access')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserCameraAccess',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cameras',
            field=models.ManyToManyField(to='cctv_model.camera'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
