# Generated by Django 4.2.4 on 2023-09-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_model', '0006_userprofile_alter_camera_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_value', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
